name = "Chaos"
author = "Cbrnex"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f629667d834aa79af31c6c863b2ccdb78cb53ccd35977f355215d095e42eba18"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
