name = "Chaos"
author = "Cbrnex"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b8fac67d986d87093c18cf8ab2d3b74deed5ef53cbf0a9916e427ced6a13dd3"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
