name = "Chaos"
author = "Cbrnex"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9424dca5cf15fb1901ffc9abc0aafe1b7a990222ab9113038589aae796608eaa"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
