name = "Chaos"
author = "Cbrnex"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5d98e43e488706c7e8c98792bfe487d7286ae9978ffcceabfb43115da015a8a"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
