name = "Chaos"
author = "Cbrnex"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90ffa1f8e44deb14579cc96533df6784df7a8af0ae48ab3576441df5ce952a8b"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
