modules_left = []

[general]
	shadow_text = false
	animations = false
    background_color = -16777216

[[modules_right]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_right.lines]
		fps = true

[[modules_right]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		server_tick = true
		packets_sent = false
		packets_received = false

[[modules_right]]
	name = "chunks"
	name_color = 43775
	value_color = 16777045
	chunks_enabled_color = 5635925
	chunks_disabled_color = 16733525
	total_chunks_color = 16755200
	enabled = true

	[modules_right.lines]
		chunk_sections = true
		chunk_culling = false
		pending_chunks = false
		pending_uploads = false
		available_buffers = false
		client_chunk_cache = false
		loaded_chunks = false
		loaded_chunks_server = false
		forceloaded_chunks = false
		spawn_chunks = false
		chunk_file = false

[[modules_right]]
	name = "entity"
	name_color = 16733525
	value_color = 16777045
	total_entities_color = 16755200
	enabled = true

	[modules_right.lines]
		particles = true
		entities = true
		monster = false
		creature = false
		ambient = false
		axolotls = false
		underground_water_creature = false
		water_creature = false
		water_ambient = false
		misc = false
		aether_surface_monster = false
		aether_darkness_monster = false
		aether_sky_monster = false
		aether_aerwhale = false

[[modules_right]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true

	[modules_right.lines]
		minecraft = true

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	memory_color_toggle = true
	time_format = "HH:mm:ss"
	enabled = true

	[modules_right.lines]
		time = true
		java_version = true
		memory_usage = true
		allocation_rate = true
		allocated_memory = true
		cpu = true
		display = true
		gpu = true
		gpu_utilization = true
		opengl_version = true
		gpu_driver = true

[[modules_right]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "help"
	name_color = 16645526
	value_color = 5636095
	enabled_color = 5635925
	disabled_color = 16733525
	enabled = true

	[modules_right.lines]
		pie_graph = true
		fps_tps = true
		help = true

