
[embeddiumplus]

	[embeddiumplus.general]
		fullscreen = "BORDERLESS"
		fpsDisplay = "ADVANCED"
		fpsDisplayGravity = "RIGHT"
		fpsDisplaySystem = "RAM"
		fpsDisplayShadow = false

	[embeddiumplus.quality]
		fog = false

	[embeddiumplus.performance]
		fontShadows = false

	[embeddiumplus.others]
		borderlessAttachModeOnF11 = "OFF"

